# Generated by Django 4.2.1 on 2023-05-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Stream Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Stream',
                'db_table': 'stream',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('funding_type', models.CharField(choices=[('EDUCATION_LOAN', 'Education Loan'), ('SELF_FINANCE', 'Self Finance')], default='SELF_FINANCE', max_length=100, verbose_name='Funding Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('interested_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='course.department', verbose_name='Interested Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='school.school', verbose_name='School')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='student.stream', verbose_name='Stream')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sslc', models.FileField(upload_to='student_certificates', verbose_name='SSLC')),
                ('plus_two', models.FileField(upload_to='student_certificates', verbose_name='Plus Two')),
                ('plus_one', models.FileField(upload_to='student_certificates', verbose_name='Plus One')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_certificates', to='student.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Certificates',
            },
        ),
    ]
